Organizations:
  - &UniversityOrg
    Name: UniversityMSP
    ID: UniversityMSP
    MSPDir: ../organizations/peerOrganizations/university.peer.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('UniversityMSP.admin','UniversityMSP.peer','UniversityMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('UniversityMSP.admin','UniversityMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('UniversityMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('UniversityMSP.peer')"
    OrdererEndpoints:
      - "orderer.example.com:7050"
